### ISSUE TITLE
Re-license hyperC to be OSD-compliant

### ISSUE THREAD

**Issue by jserv** [ibanezchen/hyperCOS-evaluate#1]
At present, the copyright notice of hyperC:

>  The source code is FREE for short-term evaluation, educational or non-commercial research only.
> Any commercial application may only be used in accordance with the corresponding license agreement.
>  Any unauthorized use, duplication, transmission, distribution,  or disclosure of this software is expressly
> forbidden.  

is far from being open source definition compliant. Is it possible to re-license?

**Comment by ibanezchen** [comment]
Let's keep this open for discussion

**Comment by socware-net** [comment]
This issue was moved to socware-net/hyperCOS-evaluate#32
