### ISSUE TITLE
build: To support Mac or not

### ISSUE THREAD

**Issue by ibanezchen** [ibanezchen/hyperCOS-evaluate#13]
_From @yoshijava on March 4, 2016 7:51_

I'd tried to build hyperCOS on my Macbook Pro. To support Mac, we have to consider 
1. ARM toolchain on Mac (homebrew will help)
2. Different parameters for many commands (find -name, sed -i, install, etc)
3. (Still trying)

So do we have the plan to support Mac environment in the future?

_Copied from original issue: ibanezchen/hyperCOS#24_

**Comment by ibanezchen** [comment]
How about implement all platform dependent util with python?

**Comment by socware-net** [comment]
This issue was moved to socware-net/hyperCOS-evaluate#22
