### ISSUE TITLE
doc: evaluation board datasheet

### ISSUE THREAD

**Issue by ibanezchen** [ibanezchen/hyperCOS-evaluate#14]
_From @rampant1018 on March 18, 2016 14:55_

e.g. pin mapping table

_Copied from original issue: ibanezchen/hyperCOS#32_

**Comment by ibanezchen** [comment]
I just share a draft with you. 
Maybe keep this issue open for following discussions.

**Comment by socware-net** [comment]
This issue was moved to socware-net/hyperCOS-evaluate#21
