### ISSUE TITLE
dbm: support thumb2 instruction parse

### ISSUE THREAD

**Issue by ibanezchen** [ibanezchen/hyperCOS-evaluate#2]
_From @ibanezchen on February 15, 2016 9:32_

the software gdb stub requires the instruction parser to recognize the thumb2 format in order to insert trapping instructions for thumb2 target.

_Copied from original issue: ibanezchen/hyperCOS#3_

**Comment by socware-net** [comment]
This issue was moved to socware-net/hyperCOS-evaluate#31
