### ISSUE TITLE
tz: Linux bootup

### ISSUE THREAD

**Issue by ibanezchen** [ibanezchen/hyperCOS-evaluate#3]
_From @ibanezchen on February 15, 2016 9:33_

Bootup Linux with a none-secure thread

_Copied from original issue: ibanezchen/hyperCOS#4_

**Comment by ibanezchen** [comment]
it's broken during a refactoring

**Comment by socware-net** [comment]
This issue was moved to socware-net/hyperCOS-evaluate#30
