### ISSUE TITLE
brd: hardware platform STM32F4

### ISSUE THREAD

**Issue by starnight** [ibanezchen/hyperCOS-evaluate#37]
I want to try the hyperC OS on STM32F4 Discovery.

What header files should I include?  What source files shuold I compile and link?
The most basic files that a developer needs is important.
And, if those information could be found in Wiki, that will be useful.

Thank you ~

**Comment by ibanezchen** [comment]
Would you like to post this on the mailing list?
Maybe we can get more people involved.

**Comment by starnight** [comment]
That's okay!

**Comment by ibanezchen** [comment]
Just push a template and linking script to bootC, branch stm32f429.
Also check the wiki
https://github.com/ibanezchen/hyperCOS-evaluate/wiki/Porting-Guide

**Comment by ibanezchen** [comment]
Add libstm32f4xx 
todo: 
- bootC 
- tmr_delay
- tmr_interrupt 
- wiki

**Comment by ibanezchen** [comment]
libsoc
commit 7b68f608b883a5c073870697babdd55690d62ced
Author: Howard Chen ibanezchen@gmail.com
Date:   Mon Sep 12 12:36:39 2016 +0800

```
add target stm32f4
```
