### ISSUE TITLE
brd: HOW to send/receive  non TCP/IP packet  using LWIP on stm32f4 

### ISSUE THREAD

**Issue by hvz2015** [ibanezchen/hyperCOS-evaluate#42]
hi 
i need to get some packets from eth interface
i am trying to receive some **(non TC/IP)** packets  from eth interface using Lwip library in intrrupt mode (not polling!).

I enabled NVIC Ethernet global interrupt and used this the callback but it never runs (GPIO_PIN_12 never toggles!)

**//---------------------------------**
void ETH_IRQHandler(void)
{
  /\* USER CODE BEGIN ETH_IRQn 0 */

  /\* USER CODE END ETH_IRQn 0 _/
  HAL_ETH_IRQHandler(&heth);
  /_ USER CODE BEGIN ETH_IRQn 1 _/
  /_ USER CODE END ETH_IRQn 1 */
}

void HAL_ETH_RxCpltCallback(ETH_HandleTypeDef _heth)
{
            HAL_GPIO_TogglePin(GPIOD, GPIO_PIN_12); 
}
*_//---------------------------------**

**by the way i am able to send non tpc/ip packets via  this function :**

int16_t f4x7_frame_push(ETH_HandleTypeDef *heth, uint8_t *buf, uint16_t len)
{
    uint8_t *buffer =  (uint8_t *)(heth->TxDesc->Buffer1Addr);

```
/* copy frame from local buf to DMA buffers */
memcpy(buffer, buf, len);

/* Prepare transmit descriptors to give to DMA*/
if (HAL_ETH_TransmitFrame(heth, len) != HAL_OK)
    return 0;

return len;
```

}

**Comment by ibanezchen** [comment]
We are planning  to support stm32f4 board and we would like the collect the user requirements.
It would be great if you can post this issue on the mailinglist: http://www.freelists.org/list/hypercos

**Comment by socware-net** [comment]
This issue was moved to socware-net/hyperCOS-evaluate#6
