### ISSUE TITLE
wiki: errors install package command

### ISSUE THREAD

**Issue by benwei** [ibanezchen/hyperCOS-evaluate#45]
Two issue on 'Get started'
https://github.com/ibanezchen/hyperCOS-evaluate/wiki/1.-Get-started

*\* Install package **
`
sudo apt-get install \
git \
...
libseccomp-dev \ 
libusbredirparser-dev \
libfdt-dev \
python-pip
`
there is a extra space at the end of line  `"libusbredirparser-dev \ "`

*\* version issue of librbd-dev **

sudo apt-get install -f librbd-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 librbd-dev : Depends: librados-dev but it is not going to be installed
              Depends: librbd1 (= 0.79-0ubuntu1) but 0.80.7-0ubuntu0.14.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by ibanezchen** [comment]
Wiki fixed,  many thanks :)
