### ISSUE TITLE
wiki - (KB) How to send a key to terminate qemu console from command line

### ISSUE THREAD

**Issue by benwei** [ibanezchen/hyperCOS-evaluate#46]
KB (Knowledge base)
http://unix.stackexchange.com/questions/167165/how-to-pass-ctrl-c-in-qemu

In your shell, before you run qemu, run "stty intr ^]" to change the interrupt key from ^c to ctrl-]
That way, ctrl-c will be passed through to qemu, but you can still interrupt qemu itself by pressing ctrl-]

**Comment by ibanezchen** [comment]
Just append this solution to wiki 

https://github.com/ibanezchen/hyperCOS-evaluate/wiki/TroubleShooting
