### ISSUE TITLE
brd: stm32f4, implement timer interface to support tickless

### ISSUE THREAD

**Issue by ibanezchen** [ibanezchen/hyperCOS-evaluate#53]
libsoc/src/stm32f4/soc.c
- irq_handler(rtc_irq)
- int tmr_init_soc(unsigned *rtcs2tick, unsigned *hz)
- unsigned soc_rtcs()
- void tmr_tickless_soc(unsigned next_expire)

**Comment by socware-net** [comment]
This issue was moved to socware-net/hyperCOS-evaluate#2
